POST http://localhost:3001/api/post/new
content-type: application/json

{   
    "title" : "2",
    "content":"2",
    "photo":"2",
    "volunteerId": "61f533d5b9b4720bb0913292"
}
###
GET http://localhost:3001/api/post/list-post
content-type: application/json

{
   
}
###

GET http://localhost:3001/api/post/search/620331d39e83c902e27586b6
content-type: application/json

{
    
}


###Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTNhMGIzMDRhMDM2YmI0ODJhNDk5YmEiLCJpYXQiOjE2MzEzMjc4MDEsImV4cCI6MTYzMTYyNzgwMX0.O7ZAOLqFuppvsQ9AYlsranjCtCsM0q2UziOviZ1iMR0
PUT http://localhost:3001/api/post/620331d39e83c902e27586b6
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTNhMGIzMDRhMDM2YmI0ODJhNDk5YmEiLCJpYXQiOjE2MzEzMjc4MDEsImV4cCI6MTYzMTYyNzgwMX0.O7ZAOLqFuppvsQ9AYlsranjCtCsM0q2UziOviZ1iMR0

{
    "title" : "1",
    "content":"5",
    "photo":"7"
    
}



### favorite
PATCH http://localhost:3000/api/post/620331d39e83c902e27586b6/favorite
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTNhMGIzMDRhMDM2YmI0ODJhNDk5YmEiLCJpYXQiOjE2MzEzMjc4MDEsImV4cCI6MTYzMTYyNzgwMX0.O7ZAOLqFuppvsQ9AYlsranjCtCsM0q2UziOviZ1iMR0

{
    "email":"duong1"
}



### DELETE for Admin
DELETE http://localhost:3000/api/post
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTNhMGIzMDRhMDM2YmI0ODJhNDk5YmEiLCJpYXQiOjE2MzEzMjc4MDEsImV4cCI6MTYzMTYyNzgwMX0.O7ZAOLqFuppvsQ9AYlsranjCtCsM0q2UziOviZ1iMR0

{
    
}

### DELETE for User
DELETE http://localhost:3000/api/post/6205c7a028d74ab73869f2bd
content-type: application/json


{
    
}
