POST http://localhost:3001/api/events/new
content-type: application/json

{   
    "orgId" : "6207c7e5d526183ed735353e",
    "nameEvent" : "Đá bóng",
    "place":"Sân vận động quốc gia Mỹ ĐÌnh",
    "description":" With it installed in the code editor you are using, you can type “lorem” and then tab and it will expand into a paragraph of Lorem Ipsum placeholder text. But it can do more! You can control how much you get, place it within HTML structure as it expands, and get different bits of it in repeated elements.",
    "photo":"https://res.cloudinary.com/ddr1jplps/image/upload/v1645360486/avatar/img_9611_1_hqqsop.jpg",
    "volunteerId":[],
    "timelines": [
        {
         "name": "4/3/2022",
         "time": "4/3/2022"             
        }
    ],
    "fee":"50000"
}
###
GET http://localhost:3001/api/events/list-event
content-type: application/json

{
   
}
###

GET http://localhost:3001/api/events/search/đ
content-type: application/json



###Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTNhMGIzMDRhMDM2YmI0ODJhNDk5YmEiLCJpYXQiOjE2MzEzMjc4MDEsImV4cCI6MTYzMTYyNzgwMX0.O7ZAOLqFuppvsQ9AYlsranjCtCsM0q2UziOviZ1iMR0
PUT http://localhost:3000/api/event/620331d39e83c902e27586b6
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTNhMGIzMDRhMDM2YmI0ODJhNDk5YmEiLCJpYXQiOjE2MzEzMjc4MDEsImV4cCI6MTYzMTYyNzgwMX0.O7ZAOLqFuppvsQ9AYlsranjCtCsM0q2UziOviZ1iMR0

{
    "title" : "1",
    "content":"5",
    "photo":"7"
    
}



### register event
POST http://localhost:3000/api/event/620331d39e83c902e27586b6/register
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTNhMGIzMDRhMDM2YmI0ODJhNDk5YmEiLCJpYXQiOjE2MzEzMjc4MDEsImV4cCI6MTYzMTYyNzgwMX0.O7ZAOLqFuppvsQ9AYlsranjCtCsM0q2UziOviZ1iMR0

{
    "email":"duong1"
}



### DELETE for Admin
DELETE http://localhost:3000/api/event/6208b4d4e7e76e2aa3e1cd1d
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTNhMGIzMDRhMDM2YmI0ODJhNDk5YmEiLCJpYXQiOjE2MzEzMjc4MDEsImV4cCI6MTYzMTYyNzgwMX0.O7ZAOLqFuppvsQ9AYlsranjCtCsM0q2UziOviZ1iMR0

{
    
}


