
###
POST http://localhost:3001/api/auth/register
content-type: application/json

{   "username":"dwg123",
    "password":"123456",
    "role":"0",
    "email":"tuan.nv19010040@st.phenikaa-uni.edu.vns",
    "phone":"+84 857324270",
    "address" :"1",
    "fullname" :"DUONG"
}
###
GET http://127.0.0.1:3001/api/auth/activation?activation_token=dsfdsfdsgfdgfdgfdgfdgdf

###
POST http://localhost:3001/api/auth/verify-phone
content-type: application/json

{
    "requestId":"40b21fcf0cc64d43bb8570ad2e40a3a3",
    "code":"2336"

}

###
POST http://localhost:3000/api/auth/login
content-type: application/json

{
    "username":"dwg12",
    "password":"123456"

   
    #"username":"admin01",
    #"password":"12345"

    # "username":"duong1",
    # "password":"12345"

}
###

POST http://localhost:3000/api/auth/refresh-token
content-type: application/json

{
    "refresh_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMDRjZTdlODMyZDRhYWQ4OGNiY2Y1NCIsImlhdCI6MTY0NDUxNzg5NSwiZXhwIjoxNjQ1MTIyNjk1fQ.o1PGERpwUwkTushsPz-ls3b-LYe58jy3_rAannNdNEw"
}
###

# GET http://localhost:3000/api/user/61f533d5b9b4720bb0913290
GET http://localhost:3000/api/auth/info
content-type: application/json
Authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMDRjZTdlODMyZDRhYWQ4OGNiY2Y1NCIsImlhdCI6MTY0NDUxNzkyMywiZXhwIjoxNjQ0NTE4ODIzfQ.Gpf03d0WSxzdb4s1lQcggrErpcmkxNIUqKMms4vt9E8

{
 
}
### 
GET http://localhost:3000/api/auth/get-all
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMDRjZTdlODMyZDRhYWQ4OGNiY2Y1NCIsImlhdCI6MTY0NDUxNzkyMywiZXhwIjoxNjQ0NTE4ODIzfQ.Gpf03d0WSxzdb4s1lQcggrErpcmkxNIUqKMms4vt9E8

{
 
}
###
GET http://localhost:3001/api/user/all_user
content-type: application/json

{
   
}

### 
PATCH http://localhost:3000/api/auth/update
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZjUzM2Q1YjliNDcyMGJiMDkxMzI5MCIsImlhdCI6MTY0NDQ3MTczOSwiZXhwIjoxNjQ0NDcyNjM5fQ.6qkSuy32pdVInCf4-rhkexLT_GOe5NO-bOAakEXDw-c

{
    "email":"hello",
    "avatar":"1.png"
}

###
POST http://localhost:3000/api/auth/forgot-password
content-type: application/json

{
    "email":"kimsoneiwillshowyou@gmail.com"
}


###
PATCH http://localhost:3000/api/auth/reset-password
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImlkIjoiNjIwMGI1OTMxYjk3YjQwOGE1ZGEzNGI1In0sImlhdCI6MTY0NDQyNzE0MCwiZXhwIjoxNjQ0NDI3NTcyfQ.EFBw_9k8ehlsfe7pFbOaEBjys6wBBXsMc_By_WdrWYM

{
    "password":"12345"
}


###


###
DELETE http://localhost:3000/api/auth/61f54d9e652f73ce0004ba01
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTNhMGIzMDRhMDM2YmI0ODJhNDk5YmEiLCJpYXQiOjE2MzEzMjc4MDEsImV4cCI6MTYzMTYyNzgwMX0.O7ZAOLqFuppvsQ9AYlsranjCtCsM0q2UziOviZ1iMR0

{
    
}

